/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortalSupportRouteImport } from './routes/portal.support'
import { Route as PortalNewRouteImport } from './routes/portal.new'
import { Route as LabScanRouteImport } from './routes/lab.scan'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as PortalSamplesSampleIdRouteImport } from './routes/portal.samples.$sampleId'
import { Route as PortalOrdersOrderIdRouteImport } from './routes/portal.orders.$orderId'
import { Route as LabSamplesSampleIdRouteImport } from './routes/lab.samples.$sampleId'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/portal/support',
  path: '/portal/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalNewRoute = PortalNewRouteImport.update({
  id: '/portal/new',
  path: '/portal/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LabScanRoute = LabScanRouteImport.update({
  id: '/lab/scan',
  path: '/lab/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/admin/customers/',
  path: '/admin/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSamplesSampleIdRoute = PortalSamplesSampleIdRouteImport.update({
  id: '/portal/samples/$sampleId',
  path: '/portal/samples/$sampleId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalOrdersOrderIdRoute = PortalOrdersOrderIdRouteImport.update({
  id: '/portal/orders/$orderId',
  path: '/portal/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSamplesSampleIdRoute = LabSamplesSampleIdRouteImport.update({
  id: '/lab/samples/$sampleId',
  path: '/lab/samples/$sampleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/admin/customers/$customerId',
    path: '/admin/customers/$customerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/users': typeof AdminUsersRoute
  '/lab/scan': typeof LabScanRoute
  '/portal/new': typeof PortalNewRoute
  '/portal/support': typeof PortalSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/lab/': typeof LabIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/lab/samples/$sampleId': typeof LabSamplesSampleIdRoute
  '/portal/orders/$orderId': typeof PortalOrdersOrderIdRoute
  '/portal/samples/$sampleId': typeof PortalSamplesSampleIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/users': typeof AdminUsersRoute
  '/lab/scan': typeof LabScanRoute
  '/portal/new': typeof PortalNewRoute
  '/portal/support': typeof PortalSupportRoute
  '/admin': typeof AdminIndexRoute
  '/lab': typeof LabIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/lab/samples/$sampleId': typeof LabSamplesSampleIdRoute
  '/portal/orders/$orderId': typeof PortalOrdersOrderIdRoute
  '/portal/samples/$sampleId': typeof PortalSamplesSampleIdRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/users': typeof AdminUsersRoute
  '/lab/scan': typeof LabScanRoute
  '/portal/new': typeof PortalNewRoute
  '/portal/support': typeof PortalSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/lab/': typeof LabIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/lab/samples/$sampleId': typeof LabSamplesSampleIdRoute
  '/portal/orders/$orderId': typeof PortalOrdersOrderIdRoute
  '/portal/samples/$sampleId': typeof PortalSamplesSampleIdRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/config'
    | '/admin/finance'
    | '/admin/users'
    | '/lab/scan'
    | '/portal/new'
    | '/portal/support'
    | '/admin/'
    | '/lab/'
    | '/portal/'
    | '/admin/customers/$customerId'
    | '/lab/samples/$sampleId'
    | '/portal/orders/$orderId'
    | '/portal/samples/$sampleId'
    | '/admin/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/config'
    | '/admin/finance'
    | '/admin/users'
    | '/lab/scan'
    | '/portal/new'
    | '/portal/support'
    | '/admin'
    | '/lab'
    | '/portal'
    | '/admin/customers/$customerId'
    | '/lab/samples/$sampleId'
    | '/portal/orders/$orderId'
    | '/portal/samples/$sampleId'
    | '/admin/customers'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/config'
    | '/admin/finance'
    | '/admin/users'
    | '/lab/scan'
    | '/portal/new'
    | '/portal/support'
    | '/admin/'
    | '/lab/'
    | '/portal/'
    | '/admin/customers/$customerId'
    | '/lab/samples/$sampleId'
    | '/portal/orders/$orderId'
    | '/portal/samples/$sampleId'
    | '/admin/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminUsersRoute: typeof AdminUsersRoute
  LabScanRoute: typeof LabScanRoute
  PortalNewRoute: typeof PortalNewRoute
  PortalSupportRoute: typeof PortalSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  LabSamplesSampleIdRoute: typeof LabSamplesSampleIdRoute
  PortalOrdersOrderIdRoute: typeof PortalOrdersOrderIdRoute
  PortalSamplesSampleIdRoute: typeof PortalSamplesSampleIdRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/portal/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/new': {
      id: '/portal/new'
      path: '/portal/new'
      fullPath: '/portal/new'
      preLoaderRoute: typeof PortalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/scan': {
      id: '/lab/scan'
      path: '/lab/scan'
      fullPath: '/lab/scan'
      preLoaderRoute: typeof LabScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/samples/$sampleId': {
      id: '/portal/samples/$sampleId'
      path: '/portal/samples/$sampleId'
      fullPath: '/portal/samples/$sampleId'
      preLoaderRoute: typeof PortalSamplesSampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/orders/$orderId': {
      id: '/portal/orders/$orderId'
      path: '/portal/orders/$orderId'
      fullPath: '/portal/orders/$orderId'
      preLoaderRoute: typeof PortalOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/samples/$sampleId': {
      id: '/lab/samples/$sampleId'
      path: '/lab/samples/$sampleId'
      fullPath: '/lab/samples/$sampleId'
      preLoaderRoute: typeof LabSamplesSampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/admin/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminUsersRoute: AdminUsersRoute,
  LabScanRoute: LabScanRoute,
  PortalNewRoute: PortalNewRoute,
  PortalSupportRoute: PortalSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
  LabIndexRoute: LabIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  LabSamplesSampleIdRoute: LabSamplesSampleIdRoute,
  PortalOrdersOrderIdRoute: PortalOrdersOrderIdRoute,
  PortalSamplesSampleIdRoute: PortalSamplesSampleIdRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
