-- Add catalog metadata columns
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS item_code text,
  ADD COLUMN IF NOT EXISTS tat_days integer,
  ADD COLUMN IF NOT EXISTS sample_solid text,
  ADD COLUMN IF NOT EXISTS sample_liquid text,
  ADD COLUMN IF NOT EXISTS packaging_instructions text;

-- Wipe existing demo data (cascade through dependent rows)
DELETE FROM public.test_results;
DELETE FROM public.test_parameters;
DELETE FROM public.test_templates;
DELETE FROM public.chain_of_custody_events;
DELETE FROM public.attachments;
DELETE FROM public.exceptions;
DELETE FROM public.shipments;
DELETE FROM public.payments;
DELETE FROM public.order_samples;
DELETE FROM public.orders;
DELETE FROM public.capacity_rules;
DELETE FROM public.products;

-- Seed catalog from spreadsheet (110 tests across 11 categories)
INSERT INTO public.products (name, category, base_price, description, item_code, tat_days, sample_solid, sample_liquid, packaging_instructions, active) VALUES
('pH', 'General', 18.0, 'Category: General | Code: pH | TAT: 5 days', 'pH', 5, '50', '100', 'Required sample size — Solid: 50g; Liquid: 100g/mL. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Iodine', 'General', 80.0, 'Category: General | Code: I | TAT: 5 days', 'I', 5, '100', '100', 'Required sample size — Solid: 100g; Liquid: 100g/mL. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Total Chloride', 'General', 50.0, 'Category: General | Code: Cl | TAT: 5 days', 'Cl', 5, '100', '100', 'Required sample size — Solid: 100g; Liquid: 100g/mL. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Moisture Content (%)', 'General', 40.0, 'Category: General | Code: Moist% | TAT: 5 days', 'Moist%', 5, '-', '100', 'Required sample size — Liquid: 100g/mL. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Insoluble Content (%)', 'General', 65.0, 'Category: General | Code: INS | TAT: 5 days', 'INS', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Solubility', 'General', 33.0, 'Category: General | Code: SOL | TAT: 5 days', 'SOL', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Particle Size Distribution - 2 Sieves', 'General', 110.0, 'Category: General | Code: PSD02 | TAT: 5 days', 'PSD02', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Particle Size Distribution - 3 Sieves', 'General', 165.0, 'Category: General | Code: PSD03 | TAT: 5 days', 'PSD03', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Particle Size Distribution - 4 Sieves', 'General', 220.0, 'Category: General | Code: PSD04 | TAT: 5 days', 'PSD04', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Particle Size Distribution - 5 Sieves', 'General', 275.0, 'Category: General | Code: PSD05 | TAT: 5 days', 'PSD05', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Particle Size Distribution - 6 Sieves', 'General', 330.0, 'Category: General | Code: PSD06 | TAT: 5 days', 'PSD06', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Particle Size Distribution - 7 Sieves', 'General', 385.0, 'Category: General | Code: PSD07 | TAT: 5 days', 'PSD07', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Particle Size Distribution - 8 Sieves', 'General', 440.0, 'Category: General | Code: PSD08 | TAT: 5 days', 'PSD08', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Particle Size Distribution - 9 Sieves', 'General', 495.0, 'Category: General | Code: PSD09 | TAT: 5 days', 'PSD09', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Particle Size Distribution - 10 Sieves', 'General', 550.0, 'Category: General | Code: PSD10 | TAT: 5 days', 'PSD10', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Particle Size Distribution - 11 Sieves', 'General', 605.0, 'Category: General | Code: PSD11 | TAT: 5 days', 'PSD11', 5, '100', '-', 'Required sample size — Solid: 100g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Silicone & Fluoride', 'General', 150.0, 'Category: General | Code: Si & F | TAT: 15 days', 'Si & F', 15, '200', '-', 'Required sample size — Solid: 200g. Pack in clean, sealed container. Label with sample ID. Avoid contamination.', true),
('Total Nitrogen', 'Fertilizer - Organic & Inorganic', 95.0, 'Category: Fertilizer | Code: Nitrogen | TAT: 5 days', 'Nitrogen', 5, '50', '50', 'Required sample size — Solid: 50g; Liquid: 50g/mL. Pack in clean, sealed container. Label with sample ID.', true),
('N-Urea', 'Fertilizer - Organic & Inorganic', 95.0, 'Fertilizer | N-Urea | 5 days', 'N-Urea', 5, '50', '50', 'Solid: 50g; Liquid: 50g/mL. Sealed container, label with sample ID.', true),
('N-Ammonium', 'Fertilizer - Organic & Inorganic', 95.0, 'Fertilizer | N-NH4 | 5 days', 'N-NH4', 5, '50', '50', 'Solid: 50g; Liquid: 50g/mL. Sealed container, label with sample ID.', true),
('Phosphorus Pentoxide', 'Fertilizer - Organic & Inorganic', 65.0, 'Fertilizer | P2O5 | 5 days', 'P2O5', 5, '50', '50', 'Solid: 50g; Liquid: 50g/mL. Sealed container, label with sample ID.', true),
('Potassium Oxide', 'Fertilizer - Organic & Inorganic', 65.0, 'Fertilizer | K2O | 5 days', 'K2O', 5, '50', '50', 'Solid: 50g; Liquid: 50g/mL. Sealed container, label with sample ID.', true),
('Magnesium Oxide', 'Fertilizer - Organic & Inorganic', 65.0, 'Fertilizer | MgO | 5 days', 'MgO', 5, '50', '50', 'Solid: 50g; Liquid: 50g/mL. Sealed container, label with sample ID.', true),
('Free Acidity', 'Fertilizer - Organic & Inorganic', 65.0, 'Fertilizer | FA | 5 days', 'FA', 5, '100', '100', 'Solid: 100g; Liquid: 100g/mL. Sealed container, label with sample ID.', true),
('pH (Fertilizer)', 'Fertilizer - Organic & Inorganic', 18.0, 'Fertilizer | pH | 5 days', 'pH', 5, '100', '100', 'Solid: 100g; Liquid: 100g/mL. Sealed container, label with sample ID.', true),
('Moisture Content (Fertilizer)', 'Fertilizer - Organic & Inorganic', 40.0, 'Fertilizer | Moist% | 5 days', 'Moist%', 5, '100', '100', 'Solid: 100g; Liquid: 100g/mL. Sealed container, label with sample ID.', true),
('Sulphate', 'Fertilizer - Organic & Inorganic', 132.0, 'Fertilizer | SO4 | 5 days', 'SO4', 5, '50', '50', 'Solid: 50g; Liquid: 50g/mL. Sealed container, label with sample ID.', true),
('Borax Trioxide', 'Fertilizer - Organic & Inorganic', 230.0, 'Fertilizer | B2O3 | 5 days', 'B2O3', 5, '200', '200', 'Solid: 200g; Liquid: 200g/mL. Sealed container, label with sample ID.', true),
('Organic Matter', 'Fertilizer - Organic & Inorganic', 100.0, 'Fertilizer | OM | 18 days', 'OM', 18, '100', '100', 'Solid: 100g; Liquid: 100g/mL. Sealed container, label with sample ID.', true),
('C/N Ratio', 'Fertilizer - Organic & Inorganic', 100.0, 'Fertilizer | C/N Ratio | 18 days', 'C/N Ratio', 18, '100', '100', 'Solid: 100g; Liquid: 100g/mL. Sealed container, label with sample ID.', true),
('Total Organic Carbon', 'Fertilizer - Organic & Inorganic', 100.0, 'Fertilizer | TOC | 18 days', 'TOC', 18, '100', '100', 'Solid: 100g; Liquid: 100g/mL. Sealed container, label with sample ID.', true),
('Arsenic (As)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | As | 5 days', 'As', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Gold (Au)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Au | 5 days', 'Au', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Boron (B)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | B | 5 days', 'B', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Barium (Ba)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Ba | 5 days', 'Ba', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Bismuth (Bi)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Bi | 5 days', 'Bi', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Cadmium (Cd)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Cd | 5 days', 'Cd', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Cobalt (Co)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Co | 5 days', 'Co', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Chromium (Cr)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Cr | 5 days', 'Cr', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Iron (Fe)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Fe | 5 days', 'Fe', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Gallium (Ga)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Ga | 5 days', 'Ga', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Mercury (Hg)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Hg | 5 days', 'Hg', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Indium (In)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | In | 5 days', 'In', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Potassium (K)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | K | 5 days', 'K', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Lithium (Li)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Li | 5 days', 'Li', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Magnesium (Mg)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Mg | 5 days', 'Mg', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Manganese (Mn)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Mn | 5 days', 'Mn', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Sodium (Na)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Na | 5 days', 'Na', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Nickel (Ni)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Ni | 5 days', 'Ni', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Phosphorus (P)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | P | 5 days', 'P', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Lead (Pb)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Pb | 5 days', 'Pb', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Sulfur (S)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | S | 5 days', 'S', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Antimony (Sb)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Sb | 5 days', 'Sb', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Selenium (Se)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Se | 5 days', 'Se', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Tin (Sn)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Sn | 5 days', 'Sn', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Strontium (Sr)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Sr | 5 days', 'Sr', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Titanium (Ti)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Ti | 5 days', 'Ti', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Zinc (Zn)', 'Heavy Metal - Aqueous', 55.0, 'Heavy Metal Aqueous | Zn | 5 days', 'Zn', 5, '20', '50', 'Solid: 20g; Liquid: 50g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Multielement (As, Cd, Cu, Mn, Pb, Sb, Sn)', 'Heavy Metal - Aqueous', 275.0, 'Heavy Metal Aqueous | Me | 5 days', 'Me', 5, '50', '500', 'Solid: 50g; Liquid: 500g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('23 Multielement Panel', 'Heavy Metal - Aqueous', 600.0, 'Heavy Metal Aqueous | Me23 | 5 days', 'Me23', 5, '50', '500', 'Solid: 50g; Liquid: 500g/mL. Acid-resistant container, sealed, label with sample ID.', true),
('Lead in Oil (Pb)', 'Heavy Metal - Organic (Oil)', 80.0, 'Heavy Metal Organic | Pb-Oil | 7 days', 'Pb-Oil', 7, '-', '50', 'Liquid 50mL, glass bottle, sealed, label with sample ID.', true),
('Sulfur in Oil (S)', 'Heavy Metal - Organic (Oil)', 80.0, 'Heavy Metal Organic | S-Oil | 7 days', 'S-Oil', 7, '-', '50', 'Liquid 50mL, glass bottle, sealed, label with sample ID.', true),
('Wear Metals Panel', 'Heavy Metal - Organic (Oil)', 250.0, 'Heavy Metal Organic | Wear | 7 days', 'Wear', 7, '-', '100', 'Liquid 100mL, glass bottle, sealed, label with sample ID.', true),
('NaCl Purity', 'Salt', 60.0, 'Salt | NaCl | 5 days', 'NaCl', 5, '100', '-', 'Solid 100g, sealed container, label with sample ID.', true),
('Sulphate in Salt', 'Salt', 70.0, 'Salt | SO4 | 5 days', 'SO4', 5, '100', '-', 'Solid 100g, sealed container, label with sample ID.', true),
('Calcium in Salt', 'Salt', 70.0, 'Salt | Ca | 5 days', 'Ca', 5, '100', '-', 'Solid 100g, sealed container, label with sample ID.', true),
('Magnesium in Salt', 'Salt', 70.0, 'Salt | Mg | 5 days', 'Mg-Salt', 5, '100', '-', 'Solid 100g, sealed container, label with sample ID.', true),
('Iron in Salt', 'Salt', 70.0, 'Salt | Fe | 5 days', 'Fe-Salt', 5, '100', '-', 'Solid 100g, sealed container, label with sample ID.', true),
('Insoluble Matter (Salt)', 'Salt', 60.0, 'Salt | INS | 5 days', 'INS-Salt', 5, '100', '-', 'Solid 100g, sealed container, label with sample ID.', true),
('Moisture (Salt)', 'Salt', 40.0, 'Salt | Moist | 5 days', 'Moist-Salt', 5, '100', '-', 'Solid 100g, sealed container, label with sample ID.', true),
('Iodine in Salt', 'Salt', 80.0, 'Salt | I | 5 days', 'I-Salt', 5, '100', '-', 'Solid 100g, sealed container, label with sample ID.', true),
('Potassium Iodate', 'Salt', 90.0, 'Salt | KIO3 | 5 days', 'KIO3', 5, '100', '-', 'Solid 100g, sealed container, label with sample ID.', true),
('Potable Water Test', 'Water', 200.0, 'Water | Potable | 7 days', 'Potable', 7, '-', '500', 'Liquid 500mL, sterile bottle, sealed, label with sample ID.', true),
('Drinking Water Quality', 'Water', 250.0, 'Water | Drink | 7 days', 'Drink', 7, '-', '500', 'Liquid 500mL, sterile bottle, sealed, label with sample ID.', true),
('Mineral Water Analysis', 'Water', 220.0, 'Water | Mineral | 7 days', 'Mineral', 7, '-', '500', 'Liquid 500mL, sterile bottle, sealed, label with sample ID.', true),
('Total Dissolved Solids', 'Water', 60.0, 'Water | TDS | 5 days', 'TDS', 5, '-', '250', 'Liquid 250mL, clean bottle, sealed, label with sample ID.', true),
('Total Hardness', 'Water', 70.0, 'Water | Hard | 5 days', 'Hard', 5, '-', '250', 'Liquid 250mL, clean bottle, sealed, label with sample ID.', true),
('Conductivity', 'Water', 50.0, 'Water | EC | 5 days', 'EC', 5, '-', '250', 'Liquid 250mL, clean bottle, sealed, label with sample ID.', true),
('Turbidity', 'Water', 50.0, 'Water | Turb | 5 days', 'Turb', 5, '-', '250', 'Liquid 250mL, clean bottle, sealed, label with sample ID.', true),
('Color & Odor', 'Water', 40.0, 'Water | Sensory | 3 days', 'Sensory-W', 3, '-', '250', 'Liquid 250mL, clean bottle, sealed, label with sample ID.', true),
('Sugar Profile (HPLC)', 'Sugar Profile', 220.0, 'Sugar | HPLC | 10 days', 'Sugar', 10, '50', '50', 'Solid 50g or Liquid 50mL, sealed container, label with sample ID.', true),
('Sensory Panel Test', 'Sensory Test', 150.0, 'Sensory | Panel | 7 days', 'Sensory', 7, '100', '100', 'Solid 100g or Liquid 100mL, food-grade sealed packaging, label with sample ID.', true),
('Energy (kcal)', 'Nutritional Fact', 120.0, 'Nutritional | Energy | 10 days', 'Energy', 10, '100', '100', 'Solid 100g or Liquid 100mL, sealed food-grade container, label with sample ID.', true),
('Total Fat', 'Nutritional Fact', 130.0, 'Nutritional | Fat | 10 days', 'Fat', 10, '100', '100', 'Solid 100g or Liquid 100mL, sealed food-grade container, label with sample ID.', true),
('Total Protein', 'Nutritional Fact', 130.0, 'Nutritional | Protein | 10 days', 'Protein', 10, '100', '100', 'Solid 100g or Liquid 100mL, sealed food-grade container, label with sample ID.', true),
('Total Carbohydrate', 'Nutritional Fact', 130.0, 'Nutritional | Carb | 10 days', 'Carb', 10, '100', '100', 'Solid 100g or Liquid 100mL, sealed food-grade container, label with sample ID.', true),
('Dietary Fiber', 'Nutritional Fact', 140.0, 'Nutritional | Fiber | 10 days', 'Fiber', 10, '100', '100', 'Solid 100g or Liquid 100mL, sealed food-grade container, label with sample ID.', true),
('Sodium (Nutritional)', 'Nutritional Fact', 90.0, 'Nutritional | Na | 10 days', 'Na-Nut', 10, '100', '100', 'Solid 100g or Liquid 100mL, sealed food-grade container, label with sample ID.', true),
('Sugar (Nutritional)', 'Nutritional Fact', 90.0, 'Nutritional | Sugar | 10 days', 'Sugar-Nut', 10, '100', '100', 'Solid 100g or Liquid 100mL, sealed food-grade container, label with sample ID.', true),
('Histamine (Seafood)', 'Seafood, Dried Seafood', 180.0, 'Seafood | Histamine | 10 days', 'Hist', 10, '100', '-', 'Solid 100g, frozen if fresh, sealed, label with sample ID.', true),
('Formaldehyde (Seafood)', 'Seafood, Dried Seafood', 200.0, 'Seafood | HCHO | 10 days', 'HCHO', 10, '100', '-', 'Solid 100g, frozen if fresh, sealed, label with sample ID.', true),
('Staphylococcus aureus', 'Microbiological', 45.0, 'Micro | S.Aus | 20 days', 'S.Aus', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true),
('Salmonella', 'Microbiological', 55.0, 'Micro | Sal | 20 days', 'Sal', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true),
('Yeast', 'Microbiological', 40.0, 'Micro | Yeast | 20 days', 'Yeast', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true),
('Mould', 'Microbiological', 40.0, 'Micro | Mould | 20 days', 'Mould', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true),
('Coliforms', 'Microbiological', 40.0, 'Micro | Coli | 20 days', 'Coli', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true),
('Escherichia coli', 'Microbiological', 45.0, 'Micro | E.Coli | 20 days', 'E.Coli', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true),
('Bacillus cereus', 'Microbiological', 45.0, 'Micro | B.Cereus | 20 days', 'B.Cereus', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true),
('Total Plate Count', 'Microbiological', 30.0, 'Micro | TPC | 20 days', 'TPC', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true),
('Listeria monocytogenes', 'Microbiological', 65.0, 'Micro | Lis Mono | 20 days', 'Lis Mono', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true),
('Total Heterotrophic', 'Microbiological', 105.0, 'Micro | T.Hete | 20 days', 'T.Hete', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true),
('Enterococci', 'Microbiological', 125.0, 'Micro | En | 20 days', 'En', 20, '100', '100', 'Solid 100g or Liquid 100mL, sterile container, refrigerated, label with sample ID.', true);